server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    group:
      dev:
        - persistence
        - jwt
        - redis
        - ai
      test:
        - persistence
        - jwt

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  cloud:
    gcp:
      project-id: sapient-helix-466420-j5
      credentials:
        path: optional:file:secret/stt.json

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  override-with-generic-response: false

---
spring:
  config:
    import: optional:file:secret/application-dev-secret.properties
    activate:
      on-profile: dev

---
spring:
  config:
    import: optional:file:../secret/application-test-secret.properties
    activate:
      on-profile: test

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
